parseGTFS ../test/gtfs/ ../test/gtfs.binary
gtfsToIntermediate ../test/gtfs.binary 20230408 20230409 false false ../test/intermediate.binary
reduceToMaximumConnectedComponent ../test/intermediate.binary ../test/intermediate.binary
reduceGraph ../test/intermediate.binary ../test/intermediate.binary
makeOneHopTransfers ../test/intermediate.binary 86400 ../test/intermediate.binary true
reduceToMaximumConnectedComponent ../test/intermediate.binary ../test/intermediate.binary
reduceGraph ../test/intermediate.binary ../test/intermediate.binary
intermediateToRAPTOR ../test/intermediate.binary ../test/raptor.binary
createLayoutGraph ../test/raptor.binary ../test/exports/raptor.layout.graph true
