parseGTFS ../../Datasets/RNV/gtfs/ ../../Datasets/RNV/gtfs.binary
gtfsToIntermediate ../../Datasets/RNV/gtfs.binary 20220315 20220316 true false ../../Datasets/RNV/intermediate.binary
reduceGraph ../../Datasets/RNV/intermediate.binary ../../Datasets/RNV/intermediate.binary
reduceToMaximumConnectedComponent ../../Datasets/RNV/intermediate.binary ../../Datasets/RNV/intermediate.binary
makeIntermediateTransitive ../../Datasets/RNV/intermediate.binary ../../Datasets/RNV/intermediate.binary
reduceGraph ../../Datasets/RNV/intermediate.binary ../../Datasets/RNV/intermediate.binary
makeOneHopTransfers ../../Datasets/RNV/intermediate.binary 86400 ../../Datasets/RNV/intermediate.binary true
intermediateToRAPTOR ../../Datasets/RNV/intermediate.binary ../../Datasets/RNV/raptor.binary
createLayoutGraph ../../Datasets/RNV/raptor.binary ../../Datasets/RNV/raptor.layout.graph true
